from unicodedata import normalize


def scrub(text: str) -> str:
    return (
        normalize(
            'NFKD',
            text
        )
        .encode('ascii', 'ignore')
        .decode('ascii')
        .replace("'", " ' ")
        .replace(r'%', r' %')
        .replace('_', ' _ ')
        .replace('`', ' ` ')
        .replace('1', ' 1 ')
        .replace('2', ' 2 ')
        .replace('3', ' 3 ')
        .replace('4', ' 4 ')
        .replace('5', ' 5 ')
        .replace('6', ' 6 ')
        .replace('7', ' 7 ')
        .replace('8', ' 8 ')
        .replace('9', ' 9 ')
        .replace('0', ' 0 ')
        .replace('~', ' ~ ')
        .replace('!', ' ! ')
        .replace('@', ' @ ')
        .replace('#', ' # ')
        .replace('$', ' $ ')
        .replace('^', ' ^ ')
        .replace('*', ' * ')
        .replace('[', ' [ ')
        .replace(']', ' ] ')
        .replace('\\', ' ')
        .replace('|', ' | ')
        .replace('(', ' ( ')
        .replace(')', ' ) ')
        .replace('=', ' = ')
        .replace('.', ' . ')
        .replace('>', ' > ')
        .replace('<', ' < ')
        .replace(';', ' ; ')
        .replace(':', ' : ')
        .replace('!', ' ! ')
        .replace('?', ' ? ')
        .replace('[', ' [ ')
        .replace(']', ' ] ')
        .replace('{', ' { ')
        .replace('}', ' } ')
        .replace('+', ' + ')
        .replace('-', ' - ')
        .replace('"', ' " ')
        .replace(',', ' , ')
        .replace('/', ' / ')
        .replace('—', ' - ')
    )
